// Student s1 = new Student();
// s1.Name = 'Adam';
// s1.Birthdate = date.newInstance(1995, 10, 10);
// s1.SchoolName = 'Oxford University';
// System.debug(s1);

// Student s2 = new Student();
// s2.Name = 'Enes';
// s2.Birthdate = date.newInstance(1993, 11, 5);
// s2.SchoolName = 'Harward University';
// System.debug(s2);

GeneralClass gc = new GeneralClass();
gc.createStudents();
gc.method2();
